name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Test stuff
        run: |
          echo "::stop-commands::ACbGa0XUVqRf9pHUWRbL"
          pwd
          echo --------------------------------
          mount
          echo --------------------------------
          df -h
          echo --------------------------------
          docker images -a
          echo --------------------------------
          echo /usr
          sudo du -sh /usr/*
          echo /opt
          sudo du -sh /opt/*
          echo /var
          sudo du -sh /var/*
          echo --------------------------------
          df -h

