name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Test stuff
        run: |
          echo "::stop-commands::ACbGa0XUVqRf9pHUWRbL"
          echo --------------------------------
          df -h
          echo --------------------------------
          echo /usr/local
          sudo du -sh /usr/local/*
          echo /usr/share
          sudo du -sh /usr/share/*
          echo /opt/hostedtoolcache
          sudo du -sh /opt/hostedtoolcache/*
          echo /opt/ghc
          sudo du -sh /opt/ghc/*
          echo /var/cache
          sudo du -sh /var/cache/*
          echo --------------------------------
          df -h
          echo --------------------------------
          dpkg -l

