name: test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Test stuff
        run: |
          echo "::stop-commands::ACbGa0XUVqRf9pHUWRbL"
          echo --------------------------------
          df -h
          echo --------------------------------
          docker image prune --all
          sudo rm -rf /usr/share/swift /usr/share/dotnet
          sudo apt-get -y purge 'clang*' 'libclang*' 'llvm-*' 'lld-*' 'lldb-*' 'dotnet-*' 'msbuild*' 'mono*' 'libmono*' ca-certificates-mono esl-erlang 'gfortran-*' 'libgfortran*' google-cloud-sdk 'ghc-*' 'cabal-*' 'zulu-*' 'mongodb-org*'
          sudo apt-get -y autoremove
          sudo apt-get clean
          echo --------------------------------
          df -h

